insert into posts(titre, description, detail, created_at, updated_at)
values('L intelligence artificielle etroite', 'ANI est classee dans la categorie d intelligence artificielle faible car elle n est specialisee que dans une gamme etroite de parametres ou de situations, comme la reconnaissance vocale ou les voitures sans conducteur, par exemple.', 'Dans l histoire de l IA, l intelligence artificielle etroite est apparue bien avant les autres types d intelligence artificielle. On pourrait faire valoir que meme certains des tout premiers systemes informatiques primitifs ont surpasse les humains dans certains types de calculs et de taches de quantification - il y a donc lieu de prouver que ces technologies constituaient une forme d intelligence artificielle etroite. De nos jours, les exemples d intelligence artificielle etroite abondent. Les ordinateurs ont reussi a surpasser les humains en jouant a des jeux complexes comme les echecs, en prenant des decisions commerciales intelligentes et dans d autres types de taches utiles et importantes. Dans cet esprit, la communaute technologique progresse vers l evolution de systemes d intelligence artificielle plus larges et plus generaux. L intelligence artificielle etroite etait une cible plus facile, et il y a encore beaucoup de debats sur la capacite des ordinateurs a exceller dans l intelligence artificielle generale, compte tenu de la complexite du cerveau humain. Cependant, des phenomenes tels que les progres du traitement du langage naturel qui permettent aux ordinateurs d ecrire des nouvelles et des romans de fiction efficaces se rapprochent des idees des humains sur ce qui constituerait un modele d intelligence artificielle forte beaucoup plus general.', '2023-05-05', '2023-05-05'), 
('L intelligence artificielle generale', 'l AGI est consideree comme une intelligence artificielle forte, car elle travaille a un niveau superieur, qui correspond a l intelligence humaine.', ' L intelligence artificielle generale (IAG) designe des systemes capables de donner de « bons » resultats dans toutes les taches cognitives propres aux etres humains ou aux animaux dits superieurs. Parfois, on elargit le concept d intelligence artificielle generale a des systemes dotes d une conscience et meme de sentiments (ce qui se rapproche de l IA forte). Cela reste toutefois a definir plus precisement et fait l objet de debats dans la communaute scientifique. Il est important d insister sur le fait qu aucun systeme d intelligence artificielle generale n existe aujourd hui. Tout comme pour l IA forte, l IA generale demeure un sujet speculatif.', '2023-05-30', '2023-05-30'),
('La superintelligence artificielle', 'Bien que ce type d IA ne soit actuellement pas developpe, l ASI signifie qu une machine dispose d une superintelligence ou qu elle est plus intelligente qu un humain.', ' La plupart des experts conviendraient que les societes n ont pas encore atteint le stade de la superintelligence artificielle. En fait, les ingenieurs et les scientifiques tentent toujours d atteindre un point qui serait considere comme l intelligence artificielle complete, où un ordinateur pourrait avoir la meme capacite cognitive qu un humain. Bien qu il y ait eu des developpements comme le superordinateur IBM d IBM battant les joueurs humains chez Jeopardy, et des appareils et accessoires fonctionnels comme Siri engageant une conversation primitive avec les gens, il n y a toujours pas d ordinateur qui puisse vraiment simuler l etendue des connaissances et des capacites cognitives d un humain adulte pleinement developpe. . Le test de Turing, developpe il y a des decennies, est encore utilise pour determiner si les ordinateurs peuvent se rapprocher de la simulation de la conversation et de la pensee humaines, ou s ils peuvent inciter d autres personnes a penser qu un ordinateur communicant est en realite un etre humain.', '2023-05-10', '2023-05-10'),
('Reinforcement learning', 'L apprentissage par renforcement reproduit le mecanisme "naturel" d acquisition des connaissances. Robot, chatbot, voiture autonome, ses applications sont multiples dans l intelligence artificielle. ', 'Le reinforcement learning (ou apprentissage par renforcement) met en œuvre des algorithmes d apprentissage qui tirent les leçons d experiences repetees en procedant par essai-erreur. Il reproduit ainsi le mecanisme "naturel" d acquisition des connaissances. Pour orienter l apprentissage dans la direction voulue, les algorithmes d apprentissage par renforcement valident les decisions prises par la machine via un mecanisme de recompense ou de penalite. On pourrait comparer la demarche à du dressage.', '2021-09-28', '2021-09-28');
insert into images(path, post_id, created_at, updated_at) values 
('avatars/binary.jpg', 1, '2022-06-26', '2022-06-26' ),
('avatars/concept.jpg', 2, '2022-07-02', '2022-07-02' ),
('avatars/hand.jpg', 3, '2022-09-20', '2021-07-30' ),
('avatars/robot.jpg', 4, '2022-09-20', '2021-07-30' );